---
title: "Mesocosm_Expt_Isotopes"
author: "JAO"
date: "May 16, 2016"
output: html_document
---

```{r setup, echo=FALSE, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
library(ggplot2) ; library(scales) ; library(gridExtra)  ; library(plyr)  ; library(dplyr) ; library(tidyverse)
library(forcats) ; library(egg)
```

```{r echo=FALSE, include=FALSE}
#######################################
### MAKE MY OWN THEME TO SAVE LINES OF CODE
theme_boxplot <- function(base_size = 12){
  theme_bw(base_size) %+replace%
    theme(legend.key.size=unit(15,"points"),
          legend.text=element_text(size=I(11)),
          legend.key=element_blank(),
          legend.title=element_blank(),
          legend.position="none",
          plot.margin=unit(c(0.5,1,0.5,1), "lines"), # respectively: top, right, bottom, left; refers to margin *outside* labels; default is c(1,1,0.5,0.5)
          panel.border=element_blank(),
          panel.spacing=unit(0,"lines"),
          axis.ticks.length=unit(1,"mm"),
          axis.text.x = element_text(margin=margin(5,0,0,0)),
          axis.text.y = element_text(margin=margin(0,5,0,0)),
          axis.text=element_text(size=13),
          axis.title.x=element_text(size=15, margin=margin(15,0,0,0)), 
          axis.title.y=element_text(size=15, angle=90, margin=margin(0,15,0,0)), 
          panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          strip.text.x=element_text(size=13, lineheight=0.5),
          strip.text.y=element_text(size=13),
          strip.background=element_rect(colour='black', fill='white'),
          axis.line.x = element_line(colour = 'black', size=0.5, linetype='solid'),
          axis.line.y = element_line(colour = 'black', size=0.5, linetype='solid'))
}  
##########################################
```

```{r  echo=FALSE, include=FALSE}
# read in the data file
Meso_expt_2013 <- read.table("../Isotope_figures.txt", head=T)

SIA_if_data <- Meso_expt_2013 %>% 
               filter(Week %in% c(1,8)) %>% # filters data to only week 1 and week 8
               mutate(Week = factor(Week),
                      Week = fct_recode(Week, " \nInitial\n " = "1",
                                              " \nFinal\n " = "8")) 

```

```{r, echo=FALSE}

SIA_if_data2 <- SIA_if_data %>%
                gather(VarType, Value, -c(Week, Chem, Oil, Core, Herbivore)) %>% 
                mutate(VarType2 = ifelse(VarType == "d13C", " 13 ", 
                                  ifelse(VarType == "d15N", " 15 ",
                                  ifelse(VarType == "d34S", " 34 ",""))),
                       VarType3 = ifelse(VarType == "d13C", " C ",
                                  ifelse(VarType == "d15N", " N ",
                                  ifelse(VarType == "d34S", " S ","")))
                       )




# VarType2 = ifelse(VarType == "d13C", paste0('delta',^13,'"C"'),
#                                   ifelse(VarType == "d15N", paste0('delta',^15,'"N"'),
#                                   ifelse(VarType == "d34S", paste0('delta',^34,'"S"'),"")))

# VarType = fct_recode(VarType, "\ndelta^13C\n" = "d13C",
#                                                      " \ndelta^15N\n " = "d15N",
#                                                      " \ndelta^34S\n " = "d34S")

```

```{r, echo=FALSE, warning=FALSE, fig.height=10, fig.width=10}

SIA_if_data2$Chem1 <- factor(SIA_if_data2$Chem, levels=c('NC', 'Core', 'Oil', 'OilCore')) # for ordering the plot

SIA_all <- ggplot(data=SIA_if_data2, aes(x=Herbivore, y=Value)) + 
                  geom_boxplot(aes(fill=Chem1)) + theme_boxplot() +
                  facet_grid(VarType2+VarType3~Week, scales="free", switch="y", 
                             labeller=label_bquote( delta ^ .(VarType2) * .(VarType3) )) +
                  xlab("Herbivore Treatment") + ylab("") + 
                  theme(legend.position = c(.88, .75),
                        panel.spacing = unit(0.25, "cm"),
                        panel.border = element_rect(colour = "black", fill=NA),
                        strip.text.y = element_text(angle=-90, lineheight=0.5, size=14, 
                                                    margin = margin(0,0.5,0,0.5, "cm"))) +
                  scale_fill_grey(start = 1, end = 0, guide=guide_legend(title = NULL),
                                  breaks=c("NC","Core","Oil","OilCore"),
                                  labels=c("No Chemicals","Dispersant","Oil","Oil + Dispersant")) +
                  scale_x_discrete(breaks=c("NG","P","S","SP"),
                                   labels=c("No\nGrazers","Insects","Snails","Insects +\nSnails")) 
  
  
SIA_all

```

```{r  echo=FALSE, include=FALSE}

SIA_if_data3 <- Meso_expt_2013 %>% 
                mutate(Week = factor(Week),
                       Week = fct_recode(Week, " \nPre-Treatment\n " = "0",
                                               " \nWeek 1 (Initial)\n " = "1",
                                               " \nWeek 4\n " = "4",
                                               " \nWeek 8 (Final)\n " = "8")) 

SIA_if_data3$Chem1 <- factor(SIA_if_data3$Chem, levels=c('NC', 'Core', 'Oil', 'OilCore')) # for ordering the plot

```

```{r, echo=FALSE, warning=FALSE, fig.height=8, fig.width=10}
#Carbon Isotope figures
d13CPlot <- ggplot(data=SIA_if_data3, aes(x=Herbivore, y=as.numeric(d13C))) + 
            geom_boxplot(aes(fill=Chem1)) + theme_boxplot() + facet_wrap(~ Week, ncol=2) +
            xlab("") + ylab(expression(paste(delta^13, "C"))) + 
            theme(legend.position=c(.9, .15),
                  axis.text.x=element_blank(),
                  panel.border = element_rect(colour = "black", fill=NA),
                  strip.text.y = element_text(angle=-90, lineheight=0.5, size=14)) +
            scale_fill_grey(start = 1, end = 0, guide=guide_legend(title = NULL),
                            breaks=c("NC","Core","Oil","OilCore"),
                            labels=c("No Chemicals","Dispersant","Oil","Oil + Dispersant")) +
            scale_x_discrete(breaks=c("NG","P","S","SP"),
                             labels=c("No\nGrazers","Insects","Snails","Insects +\nSnails")) 

#d13CPlot
```


```{r, echo=FALSE, warning=FALSE, fig.height=8, fig.width=10}
#Nitrogen Isotope Figures
d15NPlot <- ggplot(data=SIA_if_data3, aes(x=Herbivore, y=as.numeric(d15N))) + 
            geom_boxplot(aes(fill=Chem1)) + theme_boxplot() + facet_wrap(~ Week, ncol=2) +
            xlab("") + ylab(expression(paste(delta^15, "N"))) + 
            theme(legend.position="none",
                  axis.text.x=element_blank(),
                  panel.border = element_rect(colour = "black", fill=NA),
                  strip.text.y = element_text(angle=-90, lineheight=0.5,size=14)) +
            scale_fill_grey(start = 1, end = 0, guide=guide_legend(title = NULL),
                            breaks=c("NC","Core","Oil","OilCore"),
                            labels=c("No Chemicals","Dispersant","Oil","Oil + Dispersant")) +
            scale_x_discrete(breaks=c("NG","P","S","SP"),
                             labels=c("No\nGrazers","Insects","Snails","Insects +\nSnails")) 

#d15NPlot
```


```{r, echo=FALSE, warning=FALSE, fig.height=8, fig.width=10}
#Sulfur Isotope Figures
d34SPlot <- ggplot(data=SIA_if_data3, aes(x=Herbivore, y=as.numeric(d34S))) + 
            geom_boxplot(aes(fill=Chem1)) + theme_boxplot() + facet_wrap(~ Week, ncol=2) +
            xlab("Herbivore Treatment") + ylab(expression(paste(delta^34, "S"))) + 
            theme(legend.position="none",
                  panel.border = element_rect(colour = "black", fill=NA),
                  strip.text.y = element_text(angle=-90, lineheight=0.5,size=14)) +
            scale_fill_grey(start = 1, end = 0, guide=guide_legend(title = NULL),
                            breaks=c("NC","Core","Oil","OilCore"),
                            labels=c("No Chemicals","Dispersant","Oil","Oil + Dispersant")) +
            scale_x_discrete(breaks=c("NG","P","S","SP"),
                             labels=c("No\nGrazers","Insects","Snails","Insects +\nSnails")) 

#d34SPlot
```

```{r, echo=FALSE, warning=FALSE, fig.height=20, fig.width=10}
#grid.arrange(d13CPlot, d15NPlot, d34SPlot, ncol=1)

egg::ggarrange(plots=list(d13CPlot, d15NPlot, d34SPlot), 
               ncol=1, width = unit(3,"cm"), height = unit(2, "in"))

```





